language: generic
dist: bionic

install:
  # Check dead links
  - sudo apt install -qq libssl-dev
  - sudo apt install -qq nodejs-dev
  - sudo apt install -qq node-gyp
  - sudo apt install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script:
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
