language: generic
dist: bionic

script:
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links

after_failure:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_success:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

